### ISSUE TITLE
Network pies and unsuccessful requests

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#12]
On the 2 first pie, remove the empty network (wich corresponds to unsuccessful requests)

On the 3rd pie, label "None" for the empty network.

![image](https://github.com/EIDA/statsboard/assets/1147747/c361e24d-eba6-405a-b399-7716024678cc)

**Comment by jschaeff** [comment]
Make the same for the bar charts and the map.

**Comment by vpet98** [comment]
This way, let's say for the clients pie in network level when NOA node is selected, the "unique users all networks" number of clients will be different for the same number in node level for NOA node. Is this inconsistency ok? Or maybe it's better to leave the empty network and just label it "None" everywhere?

Also, it seems unlikely to be able to have different networks specifically in the map plots according to selected statistic (clients, bytes, requests), because Plotly does not support any legend for maps similar to the pies/bar plots. This means that the networks list that appears on the right of the map is built explicitly with html and cannot be "connected" to the Plotly buttons that change statistic, so that it gets also updated when these buttons are clicked.

**Comment by jschaeff** [comment]
> Or maybe it's better to leave the empty network and just label it "None" everywhere?
Or label it "unsuccessful requests" everywhere ?
> 
> Also, it seems unlikely to be able to have different networks specifically in the map plots according to selected statistic (clients, bytes, requests), because Plotly does not support any legend for maps similar to the pies/bar plots. This means that the networks list that appears on the right of the map is built explicitly with html and cannot be "connected" to the Plotly buttons that change statistic, so that it gets also updated when these buttons are clicked.

I agree, for maps, there is no need to select dynamically the networks. Just keep it simple.

**Comment by vpet98** [comment]
It is possible to select dynamically the networks in map plots, I have implemented this already. I meant that it is not possible (or is extremely complicated) to have a different list of networks to select, let's say, for bytes and requests map plots. So, it is not possible to remove the empty network from the list of the bytes map plot and keep it in the list of the requests map plot.
I am saying so because that would be the "equivalent" of removing it in the first two pies (clients and bytes) and keeping it in the 3rd pie (requests).

I'll name it "unsuccessful requests", as you stated, everywhere.
