### ISSUE TITLE
Implement network level

### ISSUE THREAD

**Issue by jschaeff** [EIDA/statsboard#3]

**Comment by vpet98** [comment]
Do we have more feedback on this one? If I implement it in similar way as node level, for some nodes the list of networks will be too long and won't be practical.

A solution would be that the user can specify into a field the networks they want to see. But this would apply only for node managers. Other users can only ask for one network at a time due to our known restrictions. If this is fine, I can implement it this way.

**Comment by jschaeff** [comment]
The easy implementation is the public view for one network. I think you can already start it.

For the authenticated view, I would suggest:

1. Field to select a node (with a dropdown list and autocompletion). Empty means "All".
2. if a node is selected, the networks selection possible values are limited to this node. It would be an autocompletion field allowing serveral values. Think about how you put tags to issues in github/gitlab. You don't list them until the first key is pressed, then you can continue to type or select one of the proposed options


It would be super cool if the networks presented to the user with autocompletion would also show some cool attributes:
- the nodes they appear in
- the policy of the statistics (green is open, red restricted)

To do this easily, maybe some new feature can be added to the /networks endpoint

**Comment by vpet98** [comment]
Basically done. Autocompletion pending, see #10.
